"""add operation_log and workshop.job_cards models

Revision ID: 5b0871f4e267
Revises: 05c8b235ccce
Create Date: 2025-08-18 15:54:23.175251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b0871f4e267'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_cards',
    sa.Column('drive_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('creation_dttm', sa.DateTime(), nullable=False),
    sa.Column('part_number', sa.String(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('modified_dttm', sa.DateTime(), nullable=False),
    sa.Column('operations', sa.JSON(), nullable=True),
    sa.Column('project', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('drive_id')
    )
    op.create_table('operation_log',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('message_dttm', sa.DateTime(), nullable=False),
    sa.Column('message', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operation_log')
    op.drop_table('job_cards')
    # ### end Alembic commands ###
